pipeline{
    agent {
    docker {
            image 'selenium/standalone-chrome'
            args '-u root'
            }
    }
    stages {
        stage('initial') {
            steps {
                sh label: 'hello skrypt', script: 'echo \'Hello\''
                sh 'echo $USERNAME'
                }
        }
            stage('set up environment') {
            steps {
                sh 'python3 --version'
                sh 'pip install --no-cache-dir -r requirements.txt'



            }
            }
            stage('run tests') {
            steps {
                sh 'echo testsin progress'
                sh 'pytest theinternet/tests/* '


            }
            }
        }
}